[[state]]
name = 'A'
start = true

[[state.transitions]]
next = 'B'
cons = 'b'
prod = '_'
move = 'L'

[[state.transitions]]
next = 'C'
cons = '*'
prod = '*'
move = 'S'

[[state]]
name = 'B'
final = false

[[state]]
name = 'C'
final = true
